<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
<header class="flex-shrink-0">
<nav class="navbar navbar-expand-md navbar-dark bg-success">
        <div class="mx-3 order-0">
            <a class="navbar-brand mx-auto" href="#">Анализатор страниц</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".dual-collapse2">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>    
            <div class="container-fluid">
        <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
            <ul class="navbar-nav me-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/">Главная</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/urls">Сайты</a>
                </li>
            </ul>
        </div>
    </div>
    </nav>
    
    <?php if (!empty($flash)): ?>
        <div class="alert alert-success" role="alert">
        <?php foreach($flash as $message): ?>
            <?php foreach($message as $string): ?>
            <p> <?= $string ?> </p>
            <?php endforeach ?>
            <?php endforeach ?>
  </div>
            </div>
    <?php endif ?>
    </header>
    <div class="table-responsive container">
    <table class="table table-success table-hover caption-top table-sm table-bordered" data-test="url">
    <caption><h1>Сайт: <?= $url[0]['name'] ?></h1></caption>
  <tbody>
    <tr>
      <th scope="row"> id </th>     
      <td><?= $url[0]['id'] ?></td>   
    </tr>
    <tr>
        <th scope="row"> URL </th>
        <td>  <?= $url[0]['name'] ?> </td>
        </tr>
    <tr>
        <th scope="row"> Добавлен </th>
        <td> <?= $url[0]['created_at'] ?> </td>
     </tbody>
</table>
</div>



<div class="table-responsive container">
    <table class="table table-success table-hover caption-top table-sm table-bordered" data-test="checks">
    <caption><h1 class="px-4">Проверки</h1>
    <form action="/urls/<?= $url[0]['id'] ?>/checks" method="post" class="row" required="">
    <div class="col-6">
                <input type="submit" class="btn btn-success btn-lg ms-3 px-5 text-uppercase mx-3" value="Проверить">
            </div>
</caption>

    <thead>
    <tr>
      <th scope="col">id</th>      
      <th scope="col">код ответа</th>
      <th scope="col">h1</th>
      <th scope="col">title</th>
      <th scope="col">description</th>
      <th scope="col">дата проверки</th>
    </tr>
  </thead>
  <tbody>
     <?php foreach($checkedUrl as $check): ?>
        <tr>
            <td> <?= $check['id'] ?> </td>
            <td> <?= $check['status_code'] ?></td>
            <td> <?= $check['h1'] ?> </td>
            <td> <?= $check['title'] ?> </td>
            <td> <?= $check['description'] ?> </td>
            <td> <?= $check['created_at'] ?> </td>
     </tr>
     <?php endforeach ?>            

  </tbody>
  
</table>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>