<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-success">
        <div class="mx-3 order-0">
            <a class="navbar-brand mx-auto" href="#">Анализатор страниц</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".dual-collapse2">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>    
            <div class="container-fluid">
        <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
            <ul class="navbar-nav me-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/">Главная</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/urls">Сайты</a>
                </li>
            </ul>
        </div>
    </div>
    </nav>
    <div class="table-responsive container">
    <table class="table table-success table-hover caption-top table-sm table-bordered" data-test="urls">
    <caption><h1>Сайты</h1></caption>
    <thead>
    <tr>
      <th scope="col">id</th>
      <th scope="col">URL</th>
      <th scope="col">Последняя проверка</th>
      <th scope="col">Код ответа</th>
    </tr>
  </thead>
  <tbody>
  <?php foreach ($urlsData as $data): ?> 
    <tr>
      <th scope="row"><?= $data['id'] ?></th>
      <td><a href="/urls/<?= $data['id'] ?>"><?= $data['name'] ?> </a></td>
      <td><?= $data['last'] ?></td> 
      <td><?= $data['code'] ?></td>       
    </tr>    
  </tbody>
  <?php endforeach ?>
</table>
</div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>